spring:
  application:
    name: sgcti

  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  tomcat:
    connection-timeout: 20000
  port: 8080
